version: '3.8'

services:
  frontend:
    container_name: mrp-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Volumen opcional para desarrollo (descomentar en dev)
      # - ./src:/app/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 